2019-02-12 20:10:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-197]
2019-02-14 09:31:06 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/ryan/Documents/sdev4CA1/data/DB.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2506)
	at org.h2.mvstore.MVStore.panic(MVStore.java:383)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:364)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/ryan/Documents/sdev4CA1/data/DB.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 29 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/ryan/Documents/sdev4CA1/data/DB.mv.db [1.4.197/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	... 23 more
2019-02-14 10:39:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP DEPARTMENT[*]"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP DEPARTMENT [42001-197]
2019-02-14 10:41:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "[*]#                         
# TO STOP EBEAN DDL GENERATION, REMOVE THIS COMMENT AND START USING EVOLUTIONS

#         

CREATE TABLE DEPARTMENT (
  DID                           INTEGER NOT NULL,
  DEP_NAME                      VARCHAR(255),
  CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DID)
) "; SQL statement:
# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table department (
  did                           integer not null,
  dep_name                      varchar(255),
  constraint pk_department primary key (did)
) [42000-197]
2019-02-14 10:41:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Sequence "DEPARTMENT_SEQ" already exists; SQL statement:
create sequence DEPARTMENT_seq increment by 1 [90035-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:57)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-02-14 10:41:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "DEPARTMENT" not found; SQL statement:
alter table employee add constraint fk_employee_dep_did foreign key (dep_did) references department (did) on delete restrict on update restrict [42102-197]
2019-02-14 10:41:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "[*]#           

ALTER TABLE EMPLOYEE DROP CONSTRAINT IF EXISTS FK_EMPLOYEE_DEP_DID "; SQL statement:
# --- !Downs

alter table employee drop constraint if exists fk_employee_dep_did [42000-197]
2019-02-14 10:41:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "[*]#           

ALTER TABLE EMPLOYEE DROP CONSTRAINT IF EXISTS FK_EMPLOYEE_DEP_DID "; SQL statement:
# --- !Downs

alter table employee drop constraint if exists fk_employee_dep_did [42000-197]
2019-02-14 10:42:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO DEPARTMENT(1[*],""Computing"")"; expected "identifier"; SQL statement:
INSERT INTO DEPARTMENT(1,"Computing") [42001-197]
2019-02-14 10:43:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "COMPUTING" not found; SQL statement:
INSERT INTO DEPARTMENT VALUES (1, Computing) [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-02-15 12:01:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ROW" not found; SQL statement:
DELETE ROW WHERE DEP_ID =1 FROM EMPLOYEE [42102-197]
2019-02-15 12:01:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ROW" not found; SQL statement:
DELETE ROW WHERE DEP_DID =1 FROM EMPLOYEE [42102-197]
2019-02-18 17:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO ADDRESS VALUES (1, '1 DB Avenue')
INSERT[*] INTO EMPLOYEE VALUES ('admin', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1)"; SQL statement:
INSERT INTO ADDRESS VALUES (1, '1 DB Avenue')
INSERT INTO EMPLOYEE VALUES ('admin', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1) [42000-197]
2019-02-18 17:54:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO ADDRESS VALUES (1, '1 DB Avenue')
INSERT[*] INTO EMPLOYEE VALUES ('admin', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1)"; SQL statement:
INSERT INTO ADDRESS VALUES (1, '1 DB Avenue')
INSERT INTO EMPLOYEE VALUES ('admin', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1) [42000-197]
2019-02-18 17:54:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO ADDRESS VALUES (1, '1 DB Avenue')
INSERT[*] INTO EMPLOYEE VALUES ('admin', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1)"; SQL statement:
INSERT INTO ADDRESS VALUES (1, '1 DB Avenue')
INSERT INTO EMPLOYEE VALUES ('admin', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1) [42000-197]
2019-02-18 17:56:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO DEPARTMENT(1[*],'Computing')
INSERT INTO EMPLOYEE VALUES ('manager', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1)"; expected "identifier"; SQL statement:
INSERT INTO DEPARTMENT(1,'Computing')
INSERT INTO EMPLOYEE VALUES ('manager', 'hulkamaniac@gmail.com', 'Hulk Hogan', 'password', 1, 1) [42001-197]
2019-02-18 17:56:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO DEPARTMENT(1[*],'Computing')"; expected "identifier"; SQL statement:
INSERT INTO DEPARTMENT(1,'Computing') [42001-197]
2019-02-18 17:56:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO DEPARTMENT(1[*],'Computing')"; expected "identifier"; SQL statement:
INSERT INTO DEPARTMENT(1,'Computing') [42001-197]
2019-02-18 17:56:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO DEPARTMENT(1[*],'Computing')"; expected "identifier"; SQL statement:
INSERT INTO DEPARTMENT(1,'Computing') [42001-197]
2019-03-04 22:02:06 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO ADDRESS (1[*], 'Colepark')"; expected "identifier"; SQL statement:
INSERT INTO ADDRESS (1, 'Colepark') [42001-197]
2019-03-04 22:02:06 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
INSERT INTO USER VALUES('manager', 'admin@gmail.com', 'Hulk', 'Hogan', 'password', 1, 1) [42102-197]
2019-03-04 22:02:49 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO EMPLOYEE VALUES('manager', 'admin@gmail.com', 'Hulk', 'Hogan', 'password', 1, 1) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-04 23:26:31 jdbc[55]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:699)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:685)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
